name: bags
version: '0.1.0.0'
synopsis: Bags
description: Bags

ghc-options:
  - -Wall
  - -Werror

dependencies:
  - aeson
  - base
  - containers
  - mtl
  - text
  - transformers

library:
  source-dirs: src
  exposed-modules: Bags
